FROM freedomx20/nginx-fpm7.4:1.0


# 将当前目录下的所有文件复制到容器中的/var/www/html目录下
COPY app/ /usr/local/app

WORKDIR /usr/local/app
RUN ln -s /usr/local/app/iptv /var/www/html/iptv



#安装mariadb数据库
RUN apt update && apt-get -y install mariadb-server net-tools vim \
    libpng-dev \
    libjpeg-dev \
    libpq-dev \
    libxml2-dev\
    zlib1g-dev \
    libzip-dev


# 安装PHP扩展
RUN apt-get install php7.4-mysqli php7.4-gd php7.4-sockets php7.4-zip php7.4-pdo php7.4-pdo_mysql
 




#设置环境变量，便于管理
ENV MARIADB_USER iptv
ENV MARIADB_PASS 123456
# 对外服务的域名或者公网IP
ENV HOST=www.dubux.ltd
#docker映射之后的端口
ENV PORT=81





RUN echo "set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936" >> /etc/vim/vimrc \
	&& echo "set termencoding=utf-8" >> /etc/vim/vimrc \
	&& echo "set encoding=utf-8" >> /etc/vim/vimrc



RUN \cp -rf php.ini /usr/local/etc/php


#初始化
RUN ["chmod","+x","db_init.sh"]
RUN bash db_init.sh


RUN ["chmod","+x","java/bin/java"]
RUN ["chmod", "+x", "install.sh"]
RUN bash install.sh $HOST $PORT

 


#导出端口
EXPOSE 3306
EXPOSE 80
 
ENTRYPOINT service apache2 restart & mysqld_safe
 




 