#!/usr/bin/env bash
echolog() {
    echo -e "\033[32m[chislash log]\033[0m" $*
}
if [ ! -f "$REQUIRED_CONFIG" ]; then
    echolog "生成/etc/clash/required.yaml文件"
    echo "secret: $SECRET_VALUE" >> /etc/clash/required.yaml
    echo "authentication:" >> /etc/clash/required.yaml
    echo " -\"$AUTHENTICATION\"" >> /etc/clash/required.yaml
    REQUIRED_CONFIG=/etc/clash/required.yaml
fi
bash /entrypoint.sh