name: Build_chislash

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PASS }}  

      - name: build_Image_PUSH
        id: build_Image_PUSH
        run : |
          git clone https://github.com/ChisBread/chislash.git
          cd chislash
          sudo docker buildx build --push --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 --tag registry.cn-hangzhou.aliyuncs.com/dubux//chislash:latest --no-cache .