name: Build_nginxwebui

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: modify
        run: |
          cd nginxWebUI_Modify
          sh copy.sh        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: build_JAR_AND_Images
        id: build_JAR_AND_Images
        run : |
          cd nginxWebUI
          mvn clean package
          dockerFile=`cat Dockerfile`
          echo $dockerFile
          docker build -t nginxwebui:latest .
          
      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PASS }}

      # Runs a single command using the runners shell
      - name: Push Docker images
        id : Push_Docker_Images
        run : |
           imageName=nginxwebui
           docker tag $imageName registry.cn-hangzhou.aliyuncs.com/dubux/$imageName:latest
           docker push registry.cn-hangzhou.aliyuncs.com/dubux/$imageName
