name: Build_chislash

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PASS }}  

      - name: Clone Codes
        id: build_Image_PUSH
        run : |
          git clone https://github.com/ChisBread/chislash.git
  
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: chislash/./
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/dubux/chislash:latest   