name: Build_Quark

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: build_JAR_AND_Images
        id: build_JAR_AND_Images
        run : |

          if [ -d "Docker-CodeWeavers_CrossOver-VNC-Modify/Quark" ]; then
            \cp -rf Docker-CodeWeavers_CrossOver-VNC-Modify/Quark/* Docker-CodeWeavers_CrossOver-VNC/Quark
          fi
          cd Docker-CodeWeavers_CrossOver-VNC/Quark
          docker build --rm -t quark-crossover-vnc .
          
      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PASS }}

      # Runs a single command using the runners shell
      - name: Push Docker images
        id : Push_Docker_Images
        run : |
           imageName=quark-crossover-vnc
           docker tag $imageName registry.cn-hangzhou.aliyuncs.com/dubux/$imageName:latest
           docker push registry.cn-hangzhou.aliyuncs.com/dubux/$imageName
